server:
  port: 4001
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:7011/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  config: classpath:log4j2.xml
spring:
  application:
    name: spring-securtity-oauth2
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/sso?useUnicode=true&amp;\
             characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        initial-size: 5
        min-idle: 5
        time-between-eviction-runs-millis: 6000
        min-evictable-idle-time-millis: 300000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
security:
  basic:
    enabled: true





