server:
  port: 33331
spring:
  application:
    name: eureka-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:7011/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    non-secure-port: ${server.port}
logging:
  config: classpath:log4j2.xml