server:
  port: 2222
spring:
  application:
    name: compute-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:7011/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  config: classpath:log4j2.xml