package com.spring.cloud.entity;

import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

@ApiModel(value = "操作用户", description = "sysStaff")
@Table(name = "sys_staff")
public class SysStaff extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.login_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "登录名")
    @Column(name = "login_name", columnDefinition = "登录名")
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.password
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "密码")
    @Column(name = "password", columnDefinition = "密码")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.real_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "操作员真实姓名")
    @Column(name = "real_name", columnDefinition = "操作员真实姓名")
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.phonePwd
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "合力捷电话密码")
    @Column(name = "phonePwd", columnDefinition = "合力捷电话密码")
    private String phonePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.phoneNo
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "合力捷电话账号")
    @Column(name = "phoneNo", columnDefinition = "合力捷电话账号")
    private String phoneno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.org_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "组织结构的Id")
    @Column(name = "org_id", columnDefinition = "组织机构的Id")
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.role_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "角色的Id")
    @Column(name = "role_id", columnDefinition = "角色的Id")
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.operator_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "操作人Id，对应staff表中的Id")
    @Column(name = "operator_id", columnDefinition = "操作人Id，对应staff表中的Id")
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    @Column(name = "create_time", columnDefinition = "创建时间")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    @Column(name = "update_time", columnDefinition = "更新时间")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.version
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "版本号")
    @Column(name = "version", columnDefinition = "版本号")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.mobile_phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "手机号")
    @Column(name = "mobile_phone", columnDefinition = "手机号")
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.status
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "状态 1正常,0删除")
    @Column(name = "status", columnDefinition = "状态 1正常,0删除")
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.change_password
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "是否修改默认密码")
    @Column(name = "change_password", columnDefinition = "是否修改默认密码")
    private Boolean changePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_staff.dfyg_employee_no
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "东方银谷员工编号")
    @Column(name = "dfyg_employee_no", columnDefinition = "东方银谷员工编号")
    private String dfygEmployeeNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.login_name
     *
     * @return the value of sys_staff.login_name
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.login_name
     *
     * @param loginName the value for sys_staff.login_name
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.password
     *
     * @return the value of sys_staff.password
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.password
     *
     * @param password the value for sys_staff.password
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.real_name
     *
     * @return the value of sys_staff.real_name
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.real_name
     *
     * @param realName the value for sys_staff.real_name
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.phonePwd
     *
     * @return the value of sys_staff.phonePwd
     * @mbggenerated
     */
    public String getPhonePwd() {
        return phonePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.phonePwd
     *
     * @param phonepwd the value for sys_staff.phonePwd
     * @mbggenerated
     */
    public void setPhonePwd(String phonepwd) {
        this.phonePwd = phonepwd == null ? null : phonePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.phoneNo
     *
     * @return the value of sys_staff.phoneNo
     * @mbggenerated
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.phoneNo
     *
     * @param phoneno the value for sys_staff.phoneNo
     * @mbggenerated
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno == null ? null : phoneno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.org_id
     *
     * @return the value of sys_staff.org_id
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.org_id
     *
     * @param orgId the value for sys_staff.org_id
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.role_id
     *
     * @return the value of sys_staff.role_id
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.role_id
     *
     * @param roleId the value for sys_staff.role_id
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.operator_id
     *
     * @return the value of sys_staff.operator_id
     * @mbggenerated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.operator_id
     *
     * @param operatorId the value for sys_staff.operator_id
     * @mbggenerated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.create_time
     *
     * @return the value of sys_staff.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.create_time
     *
     * @param createTime the value for sys_staff.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.update_time
     *
     * @return the value of sys_staff.update_time
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.update_time
     *
     * @param updateTime the value for sys_staff.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.version
     *
     * @return the value of sys_staff.version
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.version
     *
     * @param version the value for sys_staff.version
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.mobile_phone
     *
     * @return the value of sys_staff.mobile_phone
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.mobile_phone
     *
     * @param mobilePhone the value for sys_staff.mobile_phone
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.status
     *
     * @return the value of sys_staff.status
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.status
     *
     * @param status the value for sys_staff.status
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.change_password
     *
     * @return the value of sys_staff.change_password
     * @mbggenerated
     */
    public Boolean getChangePassword() {
        return changePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.change_password
     *
     * @param changePassword the value for sys_staff.change_password
     * @mbggenerated
     */
    public void setChangePassword(Boolean changePassword) {
        this.changePassword = changePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_staff.dfyg_employee_no
     *
     * @return the value of sys_staff.dfyg_employee_no
     * @mbggenerated
     */
    public String getDfygEmployeeNo() {
        return dfygEmployeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_staff.dfyg_employee_no
     *
     * @param dfygEmployeeNo the value for sys_staff.dfyg_employee_no
     * @mbggenerated
     */
    public void setDfygEmployeeNo(String dfygEmployeeNo) {
        this.dfygEmployeeNo = dfygEmployeeNo == null ? null : dfygEmployeeNo.trim();
    }
}